spring:
  datasource:
    name: eshop
    url: jdbc:mysql://127.0.0.1:3306/eshop?characterEncoding=UTF-8&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=true
    username: root
    password: 123456
  redis:
    cluster:
      nodes:
        - 192.168.11.176:7000
        - 192.168.11.176:7001
        - 192.168.11.161:7002
        - 192.168.11.161:7003
        - 192.168.11.164:7004
        - 192.168.11.164:7005
        - 192.168.11.229:7006
        - 192.168.11.229:7007
    password: 123456
    timeout: 3s
    lettuce:
      pool:
        max-active: 8
        max-idle: 4
        min-idle: 2
        max-wait: 3s
        time-between-eviction-runs: 10s
  cache:
    jcache:
      config: classpath:ehcache.xml
mybatis:
  mapper-locations: mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    lazy-loading-enabled: true
server:
  port: 8081
logging:
  level:
    org.springframework.cache: debug
