spring:
  datasource:
    name: eshop
    url: jdbc:mysql://127.0.0.1:3306/eshop?characterEncoding=UTF-8&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=true
    username: root
    password: 123456
  redis:
    cluster:
      nodes:
        - 192.168.11.176:7000
        - 192.168.11.176:7001
        - 192.168.11.161:7002
        - 192.168.11.161:7003
        - 192.168.11.164:7004
        - 192.168.11.164:7005
        - 192.168.11.229:7006
        - 192.168.11.229:7007
    password: 123456
    timeout: 3s
    lettuce:
      pool:
        max-active: 8
        max-idle: 4
        min-idle: 2
        max-wait: 3s
        time-between-eviction-runs: 10s
  cache:
    jcache:
      config: classpath:config/ehcache.xml
  kafka:
    bootstrap-servers:
      - 192.168.11.161:9092
      - 192.168.11.176:9092
      - 192.168.11.164:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
      batch-size: 100
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: eshop-cache-group
    properties:
      spring:
        json:
          trusted:
            packages: '*'
mybatis:
  mapper-locations: mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    lazy-loading-enabled: true
server:
  port: 8081
logging:
  config: classpath:config/log4j2.xml
